
export const mainTranslations = {
    pl: {
        greeting: "Witaj w Congregation Planner",
        adminLoginButton: "Logowanie administratora",
        preacherLoginButton: "Logowanie głosiciela",
        all: "Wszystkie",
        myAssignments: "Moje przydziały",
        emptyField: "Pole jest wymagane",
        invalidEmail: "Nieprawidłowy adres email",
        settingsLabel: "Ustawienia",
        confirmIdentity: 'Potwierdź swoją tożsamość, by dokonano automatycznego logowania',
        chooseColor: "Wybierz główny kolor aplikacji",
        addToCalendar: "Dodaj do kalendarza",
        newCong: "Nowe zbory",
        registeredCong: "Zarejestrowane zbory",
        successfullyAddedEventMessage: "Poprawnie dodano wydarzenie z kalendarza",
        alreadyAddedEvent: "Dodałeś już to wydarzenie do kalendarza",
        pdfInfo: "Zaloguj się w aplikacji internetowej, by wygenerowac plik do druku",
        chooseMonth: "Wybierz miesiąc",
        january: "Styczeń", 
        february: "Luty", 
        march: "Marzec", 
        april: "Kwiecień", 
        yes: "Tak",
        no: "Nie",
        may: "Maj", 
        june: "Czerwiec", 
        july: "Lipiec", 
        august: "Sierpień", 
        september: "Wrzesień", 
        october: "Październik", 
        november: "Listopad", 
        december: "Grudzień",
        monday: "Pon", 
        tuesday: "Wt", 
        wednesday: "Śro", 
        thursday: "Czw", 
        friday: "Pt", 
        saturday: "Sob", 
        sunday: "Nd",
        today: "(dzisiaj)",
        calendarPermission: "Ta aplikacja do przydatnych dla Ciebie funkcji potrzebuje dostępu do kalendarza",
        reminderIOSPermission: "Pozwól $(PRODUCT_NAME) na dostęp do przypomnień",
        faceIDPermission: "Pozwól $(PRODUCT_NAME) na używanie Face ID.",
        generatePDFError: "Nie udało się wygenerować pliku PDF.",
        dateLabel: "Data",
        dataInfo: "Dane osobiste wykorzystywane tylko do korespodencji mailowej i nie są przechowywane na żadnym serwerze"
    },
    en: {
        greeting: "Welcome to Congregation Planner",
        adminLoginButton: "Admin login",
        preacherLoginButton: "Preacher login",
        emptyField: "Field is required",
        invalidEmail: "Invalid address email",
        settingsLabel: "Settings",
        chooseMonth: "Choose month",
        newCong: "New congregations",
        registeredCong: "Registered congregations",
        alreadyAddedEvent: "You have already added this event to calendar ",
        confirmIdentity: 'Confirm your identity for automatic login',
        all: "All",
        myAssignments: "My assignments",
        yes: "Yes",
        no: "No",
        addToCalendar: "Add to calendar",
        successfullyAddedEventMessage: "Successfully added event to calendar",
        pdfInfo: "Log in to web app to generate pdf",
        january: "January", 
        february: "February", 
        march: "March", 
        april: "April", 
        may: "May", 
        june: "June", 
        july: "July", 
        august: "August", 
        september: "September", 
        october: "October", 
        november: "November", 
        december: "December",
        monday: "Mon", 
        tuesday: "Tue", 
        wednesday: "Wed", 
        thursday: "Thu", 
        friday: "Fri", 
        saturday: "Sat", 
        sunday: "Sun",
        today: "(today)",
        calendarPermission: "This app for helpful functions need permission to calendar",
        reminderIOSPermission: "Let $(PRODUCT_NAME) for accessing reminders",
        faceIDPermission: "Let $(PRODUCT_NAME) for using Face ID.",
        generatePDFError: "We could not generate PDF.",
        dateLabel: "Date",
        dataInfo: "Personal data used only for email conversation and not stored on any server"
    }
}