export const preacherRoles = {
    'can_see_meetings': 'Może wyświetlać plan zebrań',
    'can_lead_meetings': 'Może przewodniczyć zebraniu',
    'can_have_assignment': 'Może mieć zadanie na zebraniu',
    'can_edit_meetings': 'Może edytować plan zebrań',
    'can_say_prayer': 'Może pomodlić się na zebraniu',
    'can_be_reader': 'Może lektorować na zebraniu',
    'can_lead_minimeetings': 'Może poprowadzić zbiórkę',
    'can_see_minimeetings': 'Może wyświetlać plan zbiórek',
    'can_edit_minimeetings': 'Może edytować plan zbiórek',
    'can_self-assign_cartHour': 'Może zapisać się sam na wózek',
    'can_see_cartSchedule': 'Może wyświetlać plan wózka',
    'can_edit_cartSchedule': 'Może edytować plan wózka',
    'can_see_audio_video': 'Może wyświetlać plan audio-wideo i porządkowych',
    'can_be_video': 'Może być operatorem wideo',
    'can_be_audio': 'Może być operatorem audio',
    'can_take_mic': 'Może nosić mikrofony',
    'can_be_ordinal': 'Może być porządkowym',
    'can_edit_audio_video': 'Może edytować plan audio-wideo i porządkowych',
}